### ISSUE TITLE
iOS exportToJson converting zero and empty string values to "NULL"

### ISSUE THREAD

**Issue by mpat8121** [jepiqueau/capacitor-sqlite#29]
Hi again @jepiqueau,

I've just noticed that the exportToJson method is iOS is converting values that are a 0 or an empty string "" to "NULL" when exporting. As a result, when I re-import the exported JSON, the import fails due to NOT NULL CONSTRAINT failures.

An example of the exported JSON from iOS is:

```
"values":[
    [1,"Access road","NULL","NULL"],
    [2,"Accessway","NULL","NULL"],
    [3,"Air handling system","NULL","NULL"],
    [4,"Air lock","NULL","NULL"]
]
```

Where all the "NULL" strings should be zeros. 

The Android exportToJson exports the values as zeros correctly:

```
"values": [
    [1,"Access` road",0,0],
    [2,"Accessway",0,0],
    [3,"Air handling system",0,0],
    [4,"Air lock",0,0]
]
```

The same applies when the value should be an empty string:

iOS:
```
    [5, "position", ""NULL],
    [6, "company", "NULL"]
```

vs. Android:

```
    [5, "position", ""],
    [6, "company", ""]
```

Let me know if I can be of any further assistance resolving this.

**Comment by jepiqueau** [comment]
@mpat8121 this is fixed in the release 2.2.1-2 of the plugin. Thanks for your debugging help

**Comment by mpat8121** [comment]
@jepiqueau Sorry, but I'm still seeing the zeros being converted to null when exporting using release 2.2.1-2. I've tried with multiple different simulators and a real iPad device and the result is the same across all.

**Comment by mpat8121** [comment]
@jepiqueau I had to remove node_modules and package.lock.json from the ionic app and reinstall. This appears to have resolved everything. 
Thanks for your prompt fix!
